### ISSUE TITLE
Research Pack 1

### ISSUE THREAD

**Issue by 551670** [Luabee/Factories#1]
Research Pack 1 does not have a recipe. This causes a lot of LUA errors int he console.

`
[ERROR] gamemodes/factories/gamemode/factories/recipes/cl_recipes.lua:31: attempt to index local 'item' (a nil value)
  1. Update - gamemodes/factories/gamemode/factories/recipes/cl_recipes.lua:31
   2. SetRecipe - gamemodes/factories/gamemode/factories/recipes/cl_recipes.lua:15
    3. SetItem - gamemodes/factories/gamemode/factories/inventory/cl_inventory.lua:395
     4. unknown - gamemodes/factories/gamemode/factories/inventory/cl_inventory.lua:261

`

Kind Regards,
Jack Laws
COO Of Hexane Networks

**Comment by Luabee** [comment]
I’ve just patched this bug on GitHub and Steam Workshop. Thanks for the report. 😊


From: Jack Laws
Sent: Tuesday, August 8, 2017 5:55 PM
To: Luabee/Factories
Cc: Subscribed
Subject: [Luabee/Factories] Research Pack 1 (#1)

Research Pack 1 does not have a recipe. This causes a lot of LUA errors int he console.
`
[ERROR] gamemodes/factories/gamemode/factories/recipes/cl_recipes.lua:31: attempt to index local 'item' (a nil value)
1. Update - gamemodes/factories/gamemode/factories/recipes/cl_recipes.lua:31
2. SetRecipe - gamemodes/factories/gamemode/factories/recipes/cl_recipes.lua:15
3. SetItem - gamemodes/factories/gamemode/factories/inventory/cl_inventory.lua:395
4. unknown - gamemodes/factories/gamemode/factories/inventory/cl_inventory.lua:261
`
Kind Regards,
Jack Laws
COO Of Hexane Networks
